sudo: false

language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt

env:
#  - PROJECT_DIRECTORY=project1
  - PROJECT_DIRECTORY=project2
#  - PROJECT_DIRECTORY=project3

script:
  - cd $PROJECT_DIRECTORY && pytest -v --cov-config .coveragerc --cov=./

after_success:
  - codecov